language: csharp 
sudo: required
dist: trusty
mono: none
dotnet: 2.1.502
before_script:
    - dotnet restore
script:
    - dotnet test ./test/OData.QueryBuilder.Test -c $CONFIGURATION -f netcoreapp2.1
before_deploy: 
    - git checkout origin/master
    - export LAST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
    - export VERSION_ARRAY=(${LAST_TAG//./})
    - export CURRENT_TAG=${VERSION_ARRAY[0]}.${VERSION_ARRAY[1]}.${VERSION_ARRAY[2]}
    - export PACKAGE_VERSION=${CURRENT_TAG:-$DEFAULT_PACKAGE_VERSION}
    - git tag v$PACKAGE_VERSION -a
    - git push origin --tags
    - dotnet pack -c $CONFIGURATION -p:PackageVersion=$PACKAGE_VERSION
deploy:
    provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    skip_cleanup: true
    on:
#        tags: true
        branch: master
#after_deploy:
#    - dotnet nuget push OData.QueryBuilder.$PACKAGE_VERSION.nupkg -k $NUGET_API_KEY -s $NUGET_SOURCE