language: csharp 
sudo: required
dist: trusty
mono: none
dotnet: 2.1
before_script:
    - dotnet restore
script:
    - dotnet test ./test/OData.QueryBuilder.Test -c $CONFIGURATION -f netcoreapp2.1
    - dotnet pack -c $CONFIGURATION -p:PackageVersion=$VERSION
before_deploy: echo $TRAVIS_BUILD_NUMBER $CONFIGURATION $VERSION $GITHUB_OAUTH_TOKEN $NUGET_API_KEY $NUGET_SOURCE
deploy:
    provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    skip_cleanup: true
    on:
        tags: true
        branch: master
# after_deploy:
    # - dotnet nuget push OData.QueryBuilder.$VERSION.nupkg -k $NUGET_API_KEY  -s $NUGET_SOURCE